#!/usr/bin/env bash

. ./common.sh

#
# Output usage information.
#

usage() {
  cat <<-EOF

  Usage: provision <server> <user> [command]

  Example: provision staging root
           provision production john keys

  <remote> should match a [remote] section in deploy.conf

  Options:

    -C, --chdir <path>    change the working directory to <path>
    -h, --help            output help information
    -v, --version         output version

  Commands:

    all (default)         runs all provisioning scripts
    keys                  adds keys/* to root and deploy /.ssh
    deployer              creates deploy user
    environment           updates ubuntu, pulls common apt packages
    node                  installs node (and npm, part of node now)
    upstart               creates upstart script in /etc/init
    mongo                 installs mongodb
    redis                 installs redis
    nginx                 installs nginx

EOF
}

#
# Provision
#

provision() {
  config_section $ENV || abort "[$ENV] config section not found in deploy.conf"
  test -z "$ENV" && usage && exit

  INSTANCE=`config_get instance`
  echo "INSTANCE: $INSTANCE"
  case $INSTANCE in
    linode) invoke "./linode/provision"; ;;
    joyent) invoke "./joyent/provision"; ;;
    *) abort "instance type must be specified in deploy.conf"; ;;
  esac
}

while test $# -ne 0; do
  arg=$1; shift
  case $arg in
    -h|--help) usage; exit ;;
    -V|--version) version; exit ;;
    config) config $@; exit ;;
    *)
      if test -z "$ENV"; then
        ENV=$arg;
      else
        REF="$REF $arg";
      fi
      ;;
  esac
done


provision