#!/usr/bin/env bash

. ./common.sh

#
# Output usage information.
#

usage() {
  cat <<-EOF

  Usage: provision <server> <user> [command]

  Example: provision staging root
           provision production john keys

  <remote> should match a [remote] section in deploy.conf

  Options:

    -C, --chdir <path>    change the working directory to <path>
    -h, --help            output help information
    -v, --version         output version

  Commands:

    all (default)         runs all provisioning scripts
    keys                  adds keys/* to root and deploy /.ssh
    deployer              creates deploy user
    environment           updates ubuntu, pulls common apt packages
    node                  installs node (and npm, part of node now)
    upstart               creates upstart script in /etc/init
    mongo                 installs mongodb
    redis                 installs redis
    nginx                 installs nginx

EOF
}

#
# Provision
#

provision() {
  INSTANCE=`config_get instance`
  case $INSTANCE in
    linode) invoke "./linode/provision"; ;;
    joyent) invoke "./joyent/provision"; ;;
    *) abort "instance type must be specified in deploy.conf"; ;;
  esac
}

provision